
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8 
  username: MyApp 
  password: 
  host: localhost 

development:
  <<: *default
  adapter: postgresql
  database: MyApp_development

test:
  <<: *default
  adapter: postgresql
  database: MyApp_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV[postgres://mhwolqeobgymqh:4957aeb89ffac14d90cea10815e031648b091487cd75775df3156770a4a8dfa2@ec2-23-20-224-166.compute-1.amazonaws.com:5432/d88o6evpmkkl91'] %> 
