
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8 
  username: MyApp 
  password: 
  host: localhost 

development:
  <<: *default
  adapter: postgresql
  database: MyApp_development

test:
  <<: *default
  adapter: postgresql
  database: MyApp_test

production:
  <<: *default
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> 
